version: "3.8"  

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: meu-backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge